steps:
- name: 'Build Image'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/minimal_nim_container', '.' ]
- name: "Update Instance"
  # args: ["app", "deploy", "--image-url=gcr.io/$PROJECT_ID/minimal_nim_container"]
  args: ["compute", "instances", "update-container", "nim-server", "--container-image", "gcr.io/$PROJECT_ID/minimal_nim_container"]
images:
- 'gcr.io/$PROJECT_ID/minimal_nim_container'